/*
 * Moonlight for HarmonyOS
 * Copyright (C) 2024-2025 Moonlight/AlkaidLab
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

export const DEFAULT_HTTP_PORT = 47989;
export const DEFAULT_HTTPS_PORT = 47984;
export const MAX_PORT = 65535;
